# Generated by Django 4.1.6 on 2023-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_welcomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepage',
            name='welcome_greetings',
            field=models.CharField(default='Bienvenido!!!', max_length=300),
            preserve_default=False,
        ),
    ]
