# Generated by Django 4.1.6 on 2023-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('teaches', models.CharField(choices=[('Funcional', 'Funcional'), ('Spinning', 'Spinning'), ('Crossfit', 'Crossfit'), ('Arte-Marcial', 'Arte-Marcial')], max_length=50)),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
    ]
