# Generated by Django 4.1.6 on 2023-02-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='is_free',
        ),
    ]
