# Generated by Django 4.1.6 on 2023-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
